version: "3.8"
services:
  api:
    build: .
    container_name: test-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    entrypoint: ["python", "/app/app/main.py"]
    command: ["api"]