# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  # Run this workflow manually from the Actions tab on Repo homepage
  workflow_dispatch:

jobs:
  
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        # VPS IP
        host: ${{ secrets.VPS_SSH_HOST }}
                  
        # VPS username
        username: ${{ secrets.VPS_SSH_USERNAME }}
                  
        # SSH key (copy it from your local machine)
        key: ${{ secrets.VPS_SSH_SECRET }}
        
        # SSH port
        port: ${{ secrets.VPS_SSH_PORT }}
        # passphrase
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        
        script: |
          echo "list env"
          echo ${{ secrets.VPS_SSH_HOST }}
          echo ${{ secrets.VPS_SSH_USERNAME }}
          echo ${{ secrets.VPS_SSH_SECRET }}
          echo ${{ secrets.VPS_SSH_PORT }}
          echo ${{ secrets.SSH_PASSPHRASE }}
          echo ${{ secrets.PROJECT_PATH }}
          echo "end of list env"
          cd ${{ secrets.PROJECT_PATH }}
          git pull origin master
          docker compose down
          echo "Starting containers..."
          docker compose up -d
          echo "Deleting old image(s)..."
          docker image prune -a -f