# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI/CD with Docker Compose

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: actions/setup-python@v3
      with:
        python-version: 3.x

    - name: Check for changes in Dockerfile
      run: git diff --quiet HEAD -- Dockerfile || touch ./docker-changed

    - name: Build Docker image
      run: |
        if [ -f ./docker-changed ]; then
          docker build -t my-fastapi-app .
          rm ./docker-changed
        else
          echo "No changes in Dockerfile. Using existing image."
        fi

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: actions/setup-python@v3
      with:
        python-version: 3.x

    - name: Run Docker Compose
      run: docker-compose up -d
